### ISSUE TITLE
Compile error for chamfer_dist

### ISSUE THREAD

**Issue by YellowOrz** [Ivan-Tang-3D/Any2Point#2]
I am using ubuntu24.04, cuda 11.3, gcc & g++ 10.5. When compiling chamfer_dist, I encountered the following compilation error.
```
[1/1] /usr/local/cuda/bin/nvcc  -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/Any2Point/include/python3.7m -c -c /home/orz/Projects/Any2Point/Any2Point_CLIP_Lang/cpp/chamfer_dist/chamfer.cu -o /home/orz/Projects/Any2Point/Any2Point_CLIP_Lang/cpp/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/orz/Projects/Any2Point/Any2Point_CLIP_Lang/cpp/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o 
/usr/local/cuda/bin/nvcc  -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/Any2Point/include/python3.7m -c -c /home/orz/Projects/Any2Point/Any2Point_CLIP_Lang/cpp/chamfer_dist/chamfer.cu -o /home/orz/Projects/Any2Point/Any2Point_CLIP_Lang/cpp/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/usr/include/linux/types.h:12:27: error: expected initializer before ‘__s128’
   12 | typedef __signed__ __int128 __s128 __attribute__((aligned(16)));
      |                           ^~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/Any2Point/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/opt/miniconda3/envs/Any2Point/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

**Comment by YellowOrz** [comment]
Temporarily commenting out the line of code that reports the error allows the compilation to run normally.

**Comment by Ivan-Tang-3D** [comment]
OKay, It's Nice!
